function setup
  fish_vi_key_bindings

  abbr c 'xclip -selection clipboard'
  abbr dc 'docker-compose'
  abbr do 'docker'
  abbr l 'exa -lah'
  abbr r './run'
  abbr R 'less -R'
  abbr q 'jq -C . | less -R'
  abbr rm 'rm -I'

  abbr s 'git status'
  abbr d 'git diff'
  abbr g 'git'
  abbr ga 'git add'
  abbr gamd 'git commit -a --amend --no-edit'
  abbr gb 'git blame'
  abbr gbr 'git branch'
  abbr gci 'git commit'
  abbr gcl 'git clone'
  abbr gco 'git checkout'
  abbr gl 'git log'
  abbr glol 'git log --all --graph --decorate --oneline'
  abbr glols 'git log --all --graph --decorate --oneline --simplify-by-decoration'
  abbr glp 'git log -p'
  abbr gm 'git merge'
  abbr gp 'git pull'
  abbr gr 'git rebase'
  abbr gs 'git show'
  abbr gst 'git stash'
  abbr gu 'git push'
end
