#!/usr/bin/env bash

pattern='.venv/bin/pip'
venv_pip="$(look-up "$pattern")"

if test "$venv_pip" == ''; then
    echo "No \`$pattern\` was found."
    echo 'Use `lpip` to install into `~/.python`.'
    exit 1
fi

"$venv_pip" "$@"
